import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("عقود عمليات المنتج والمراجعة", () => {
  it("يعرض سجلًا محدودًا بنطاق المتجر ويعيد الصور المستبعدة للمراجعة", () => {
    const routerSource = readFileSync(new URL("./products.ts", import.meta.url), "utf8");
    const dbSource = readFileSync(new URL("../products/db.ts", import.meta.url), "utf8");
    expect(routerSource).toContain("operations: protectedProcedure");
    expect(routerSource).toContain("restoreMediaToColorReview");
    expect(routerSource).toContain("setPrimaryMedia");
    expect(dbSource).toContain("listProductOperations");
    expect(dbSource).toContain("innerJoin(products");
    expect(dbSource).toContain("media_color_review_restored");
    expect(dbSource).toContain("primary_media_changed");
    expect(routerSource).toContain("restoreFromArchive");
    expect(routerSource).toContain("archive: protectedProcedure");
    expect(routerSource).toContain("activateMany: protectedProcedure");
    expect(routerSource).toContain("activatedProductIds");
    expect(routerSource).toContain("Promise.allSettled");
    expect(routerSource).toContain("isReadyForActivation");
    expect(routerSource).toContain("readinessReasons");
    expect(routerSource).toContain("getProductReviewReadiness");
    expect(dbSource).toContain("product_archived");
    expect(dbSource).toContain("product_restored_from_archive");
    expect(routerSource).toContain("updateDetails: protectedProcedure.input");
    expect(routerSource).not.toContain('status: z.enum(["draft", "needs_review", "ready", "archived"]).optional(),');
    expect(routerSource).toContain("sizeLabels: z.array(z.string().trim().min(1).max(80)).max(30).optional()");
    expect(dbSource).toContain("sizeLabels: input.sizeLabels?.length ? JSON.stringify(input.sizeLabels) : null");
    expect(routerSource).toContain("uploadManualMedia: protectedProcedure");
    expect(routerSource).toContain("video\\/(mp4|webm|quicktime)");
    expect(routerSource).toContain("generateAutomaticColorSuggestion");
    expect(routerSource).toContain("generateAutomaticColorSuggestionsMany");
    expect(routerSource).toContain("assignUnlinkedMediaToColorMany");
    expect(routerSource).toContain("totalMediaCount");
    expect(routerSource).toContain(")).min(0).max(250)");
    expect(dbSource).toContain("addManualProductVideo");
    expect(dbSource).toContain('mediaType: "video"');
    expect(routerSource).toContain("reviewMediaCount");
    expect(routerSource).toContain("reviewMediaPreviews");
    expect(routerSource).toContain("!media.variantId && !media.colorVerified");
  });
});
