import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Activity, CheckCircle2, CircleAlert, CloudCog, KeyRound, LoaderCircle, Plus, RefreshCcw, Save, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const providerLabels = { openai: "OpenAI", gemini: "Gemini", anthropic: "Claude" } as const;
const taskLabels: Record<string, string> = { customer_reply_fast: "رد الزبون السريع", customer_reply_escalation: "رد الزبون المعقد", product_image_analysis: "تحليل صورة المنتج", customer_image_analysis: "تحليل صورة الزبون", image_product_matching: "مطابقة الصورة بالمنتج", marketing_analysis: "تحليل التسويق", content_generation: "إنشاء المحتوى" };

type Provider = keyof typeof providerLabels;
type ConnectionForm = { id?: number; provider: Provider; displayName: string; apiKey: string; enabled: boolean };
const emptyConnection: ConnectionForm = { provider: "openai", displayName: "", apiKey: "", enabled: false };

export default function AiPlatformSettings() {
  const overview = trpc.ai.overview.useQuery(undefined, { retry: false });
  const usage = trpc.ai.usage.useQuery({ limit: 40 }, { retry: false });
  const [form, setForm] = useState<ConnectionForm>(emptyConnection);
  const [editing, setEditing] = useState<number | null>(null);
  const [modelsConnectionId, setModelsConnectionId] = useState<number | null>(null);
  const models = trpc.ai.models.useQuery({ connectionId: modelsConnectionId ?? 0 }, { enabled: Boolean(modelsConnectionId), retry: false });
  const utils = trpc.useUtils();
  const saveConnection = trpc.ai.saveConnection.useMutation({ onSuccess: async () => { await utils.ai.overview.invalidate(); resetConnection(); toast.success("تم حفظ الاتصال؛ اختبر المفتاح لتفعيله."); }, onError: error => toast.error(error.message) });
  const testConnection = trpc.ai.testConnection.useMutation({ onSuccess: async data => { await utils.ai.overview.invalidate(); toast.success(`نجح الاتصال وظهر ${data.modelCount} نموذجًا.`); }, onError: error => toast.error(error.message) });
  const updateTask = trpc.ai.updateTask.useMutation({ onSuccess: async () => { await utils.ai.overview.invalidate(); toast.success("تم حفظ مسار المهمة."); }, onError: error => toast.error(error.message) });
  const connections = overview.data?.connections ?? [];
  const tasks = overview.data?.tasks ?? [];
  const verifiedConnections = connections.filter(connection => connection.status === "verified");
  const usageCost = overview.data?.summary.estimatedCost ?? "0";

  function resetConnection() { setForm(emptyConnection); setEditing(null); }
  function editConnection(connection: typeof connections[number]) { setEditing(connection.id); setForm({ id: connection.id, provider: connection.provider, displayName: connection.displayName, apiKey: "", enabled: connection.enabled }); }
  function submitConnection() { if (!form.displayName.trim()) return toast.error("أدخل اسم الاتصال."); if (!form.id && !form.apiKey.trim()) return toast.error("أدخل مفتاح API عند إنشاء الاتصال."); saveConnection.mutate({ id: form.id, provider: form.provider, displayName: form.displayName, apiKey: form.apiKey || undefined, enabled: form.enabled, connectionType: "api_key" }); }

  if (overview.isLoading) return <div dir="rtl" className="grid min-h-[420px] place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-primary" /></div>;
  if (overview.isError) return <div dir="rtl" className="rounded-2xl border border-destructive/20 bg-destructive/5 p-6 text-sm text-destructive">لا يمكن عرض مركز AI إلا لمدير المنصة.</div>;

  return <div dir="rtl" className="mx-auto max-w-7xl space-y-5 pb-10">
    <header className="overflow-hidden rounded-[1.8rem] border border-[#e4dfd1] bg-[radial-gradient(circle_at_90%_8%,#e8f1ed,transparent_35%),linear-gradient(135deg,#fffdf9,#f3f8f5)] px-5 py-6 shadow-[0_10px_28px_rgba(41,63,53,0.06)] sm:px-7">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold tracking-[0.13em] text-[#9a7b3e]">PLATFORM AI CONTROL CENTER</p><h1 className="mt-1.5 flex items-center gap-2 text-2xl font-bold text-[#233a33]"><Sparkles className="h-6 w-6 text-[#1d5a4d]" />مركز إدارة تكاملات الذكاء الاصطناعي</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6d7a72]">إدارة اتصالات OpenAI وGemini، ربط المهام بالنماذج، وحماية المفاتيح مع سجل استخدام مستقل.</p></div><Badge className="h-fit rounded-full bg-[#e7f4ee] px-3 py-1.5 text-[#1d5a4d]">مدير المنصة فقط</Badge></div>
    </header>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <SummaryCard icon={<ShieldCheck />} label="اتصالات موثقة" value={`${verifiedConnections.length} / ${connections.length}`} tone="green" />
      <SummaryCard icon={<Activity />} label="استدعاءات آخر 30 يومًا" value={String(overview.data?.summary.calls ?? 0)} tone="gold" />
      <SummaryCard icon={<CloudCog />} label="التكلفة التقديرية" value={`${usageCost} USD`} tone="blue" />
      <SummaryCard icon={<CircleAlert />} label="العمليات الفاشلة" value={String(overview.data?.summary.failed ?? 0)} tone="red" />
    </section>

    <Tabs defaultValue="connections" dir="rtl" className="space-y-4"><TabsList className="grid h-auto w-full grid-cols-3 rounded-xl bg-muted/60 p-1"><TabsTrigger value="connections">المزودون والأسرار</TabsTrigger><TabsTrigger value="tasks">ربط المهام</TabsTrigger><TabsTrigger value="usage">الاستخدام والتكلفة</TabsTrigger></TabsList>
      <TabsContent value="connections" className="grid gap-4 lg:grid-cols-[1.05fr,1.35fr]">
        <Card className="border-border/70 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><KeyRound className="h-4 w-4 text-primary" />{editing ? "تدوير اتصال" : "إضافة اتصال"}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>المزود</Label><Select value={form.provider} onValueChange={value => setForm(current => ({ ...current, provider: value as Provider }))} disabled={Boolean(editing)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="openai">OpenAI</SelectItem><SelectItem value="gemini">Gemini</SelectItem><SelectItem value="anthropic">Claude لاحقًا</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>اسم الاتصال</Label><Input value={form.displayName} onChange={event => setForm(current => ({ ...current, displayName: event.target.value }))} placeholder="OpenAI Production" /></div></div><div className="space-y-2"><Label>{editing ? "مفتاح جديد اختياري" : "API Key"}</Label><Input type="password" autoComplete="new-password" value={form.apiKey} onChange={event => setForm(current => ({ ...current, apiKey: event.target.value }))} placeholder={editing ? "اتركه فارغًا للإبقاء على المفتاح" : "يُرسل للخادم ولا يُعاد عرضه"} /></div><div className="flex items-center justify-between rounded-xl border bg-muted/25 p-3"><div><p className="text-sm font-medium">السماح باستخدام الاتصال</p><p className="text-xs text-muted-foreground">لا يُفعل فعليًا قبل نجاح الاختبار.</p></div><Switch checked={form.enabled} onCheckedChange={enabled => setForm(current => ({ ...current, enabled }))} /></div><div className="flex gap-2"><Button onClick={submitConnection} disabled={saveConnection.isPending} className="gap-2"><Save className="h-4 w-4" />حفظ آمن</Button>{editing ? <Button variant="outline" onClick={resetConnection}>إلغاء</Button> : null}</div><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-3 text-xs leading-5 text-amber-900">المفتاح يُخزن مشفرًا في الخادم ولا يظهر في الواجهة أو سجل التدقيق. لا تضعه في الكود أو ملفات المشروع.</div></CardContent></Card>
        <Card className="border-border/70 shadow-sm"><CardHeader><CardTitle className="text-base">الاتصالات المسجلة</CardTitle></CardHeader><CardContent className="space-y-3">{connections.length === 0 ? <EmptyState label="لم تتم إضافة أي اتصال بعد." /> : connections.map(connection => <div key={connection.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><KeyRound className="h-4 w-4" /></div><div><p className="font-semibold">{connection.displayName}</p><p className="text-xs text-muted-foreground">{providerLabels[connection.provider]} · {connection.lastTestedAt ? `آخر اختبار ${new Date(connection.lastTestedAt).toLocaleString("ar-IQ")}` : "لم يُختبر بعد"}</p><div className="mt-1 flex gap-2"><StatusBadge status={connection.status} /><Badge variant="outline">{connection.enabled ? "مفعّل" : "متوقف"}</Badge></div></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => testConnection.mutate({ id: connection.id, provider: connection.provider })} disabled={testConnection.isPending} className="gap-1"><RefreshCcw className="h-3.5 w-3.5" />اختبار</Button><Button variant="outline" size="sm" onClick={() => { setModelsConnectionId(connection.id); void models.refetch(); }} className="gap-1">النماذج</Button><Button variant="ghost" size="sm" onClick={() => editConnection(connection)}>تعديل</Button></div></div>)}{modelsConnectionId ? <div className="rounded-xl bg-muted/40 p-3 text-xs"><div className="mb-2 flex items-center justify-between"><b>النماذج المتاحة</b><button className="text-muted-foreground" onClick={() => setModelsConnectionId(null)}>إغلاق</button></div>{models.isLoading ? "جارٍ التحميل…" : models.isError ? <span className="text-destructive">تعذر جلب النماذج</span> : <div className="flex max-h-32 flex-wrap gap-1.5 overflow-auto">{(models.data ?? []).slice(0, 80).map(model => <Badge key={model.id} variant="outline" className="font-mono text-[10px]">{model.id}</Badge>)}</div>}</div> : null}</CardContent></Card>
      </TabsContent>
      <TabsContent value="tasks"><TaskTable tasks={tasks} connections={connections} onSave={input => updateTask.mutate(input)} pending={updateTask.isPending} /></TabsContent>
      <TabsContent value="usage"><UsageTable rows={usage.data ?? []} /></TabsContent>
    </Tabs>
  </div>;
}

function SummaryCard({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: "green" | "gold" | "blue" | "red" }) { const colors = { green: "bg-emerald-50 text-emerald-700", gold: "bg-amber-50 text-amber-700", blue: "bg-sky-50 text-sky-700", red: "bg-rose-50 text-rose-700" }; return <Card className="border-border/70 shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${colors[tone]}`}>{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-0.5 text-lg font-bold">{value}</p></div></CardContent></Card>; }
function StatusBadge({ status }: { status: string }) { const meta: Record<string, { label: string; className: string }> = { verified: { label: "موثق", className: "bg-emerald-50 text-emerald-700" }, untested: { label: "غير مختبر", className: "bg-amber-50 text-amber-700" }, needs_attention: { label: "يحتاج مراجعة", className: "bg-rose-50 text-rose-700" }, disabled: { label: "متوقف", className: "bg-slate-100 text-slate-700" } }; const item = meta[status] ?? meta.untested; return <Badge className={item.className}>{item.label}</Badge>; }
function EmptyState({ label }: { label: string }) { return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{label}</div>; }
function TaskTable({ tasks, connections, onSave, pending }: { tasks: any[]; connections: any[]; onSave: (input: any) => void; pending: boolean }) { return <Card className="border-border/70 shadow-sm"><CardHeader><CardTitle className="text-base">خريطة المهام والمزودين</CardTitle><p className="text-xs text-muted-foreground">تغيير هذه الخريطة لا يحتاج نشر كود جديد. لا يمكن تفعيل مهمة قبل توثيق الاتصال.</p></CardHeader><CardContent className="space-y-3">{tasks.map(item => <TaskRow key={item.task} item={item} connections={connections} onSave={onSave} pending={pending} />)}</CardContent></Card>; }
function TaskRow({ item, connections, onSave, pending }: { item: any; connections: any[]; onSave: (input: any) => void; pending: boolean }) { const [draft, setDraft] = useState(item); useEffect(() => setDraft(item), [item]); const selected = connections.find(connection => connection.id === draft.providerConnectionId); return <div className="grid gap-3 rounded-xl border p-4 lg:grid-cols-[1.3fr,1fr,1.2fr,auto] lg:items-end"><div><p className="font-semibold">{taskLabels[item.task] ?? item.task}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.task}</p></div><div className="space-y-2"><Label className="text-xs">الاتصال</Label><Select value={draft.providerConnectionId ? String(draft.providerConnectionId) : "none"} onValueChange={value => setDraft({ ...draft, providerConnectionId: value === "none" ? null : Number(value) })}><SelectTrigger><SelectValue placeholder="غير مربوط" /></SelectTrigger><SelectContent><SelectItem value="none">غير مربوط</SelectItem>{connections.map(connection => <SelectItem key={connection.id} value={String(connection.id)}>{connection.displayName} · {providerLabels[connection.provider as Provider]}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label className="text-xs">النموذج</Label><Input value={draft.model} onChange={event => setDraft({ ...draft, model: event.target.value })} placeholder="model-id" /></div><div className="flex items-center gap-2"><Switch checked={draft.enabled} onCheckedChange={enabled => setDraft({ ...draft, enabled })} /><Button size="sm" onClick={() => onSave({ ...draft, monthlyBudget: draft.monthlyBudget ?? null })} disabled={pending || (draft.enabled && !selected)} className="gap-1"><Save className="h-3.5 w-3.5" />حفظ</Button></div></div>; }
function UsageTable({ rows }: { rows: any[] }) { if (!rows.length) return <EmptyState label="لا توجد عمليات مسجلة بعد." />; return <Card className="border-border/70 shadow-sm"><CardHeader><CardTitle className="text-base">آخر عمليات AI</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="p-3">المزود</th><th className="p-3">المهمة</th><th className="p-3">النموذج</th><th className="p-3">الرموز</th><th className="p-3">التكلفة</th><th className="p-3">الحالة</th><th className="p-3">الوقت</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b last:border-0"><td className="p-3">{providerLabels[row.provider as Provider] ?? row.provider}</td><td className="p-3">{taskLabels[row.task] ?? row.task}</td><td className="p-3 font-mono text-xs">{row.model}</td><td className="p-3">{row.inputTokens + row.outputTokens}</td><td className="p-3">{row.estimatedCost} {row.currency}</td><td className="p-3"><Badge variant="outline">{row.status}</Badge></td><td className="p-3 text-xs text-muted-foreground">{new Date(row.createdAt).toLocaleString("ar-IQ")}</td></tr>)}</tbody></table></CardContent></Card>; }
