import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CustomerBotNav, SafetyNotice } from "@/components/customerBot/CustomerBotNav";
import CustomerBotCommandAssistant from "@/pages/CustomerBotCommandAssistant";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BookOpenText, CheckCircle2, FileAudio, FileText, FolderOpen, Loader2, Plus, Radio, ShieldCheck, UploadCloud, WandSparkles } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const statusStyle: Record<string, string> = { draft: "bg-amber-50 text-amber-800", approved: "bg-emerald-50 text-emerald-800", archived: "bg-slate-100 text-slate-700", rejected: "bg-rose-50 text-rose-800" };
const statusLabel: Record<string, string> = { draft: "مسودة", approved: "معتمدة", archived: "مؤرشفة", rejected: "مرفوضة" };
const categoryLabel: Record<string, string> = { dialect_style: "أسلوب الكلام واللهجة", reply_example: "نموذج رد", knowledge: "بطاقة معرفة", sales_playbook: "خطوات البيع", test_case: "اختبار للبوت", guardrail: "حماية وممنوعات", knowledge_gap: "معلومة ناقصة" };
const tabs = [
  { id: "cards", label: "بطاقات المعرفة", icon: BookOpenText },
  { id: "assistant", label: "مساعد التعليم", icon: WandSparkles },
  { id: "behavior", label: "السلوك واللهجة", icon: Radio },
  { id: "sources", label: "مصادر التدريب", icon: UploadCloud },
  { id: "drafts", label: "المسودات والمراجعة", icon: FolderOpen },
] as const;
type TabId = (typeof tabs)[number]["id"];

export default function CustomerBotLearning() {
  const [location, setLocation] = useLocation();
  const query = location.includes("?") ? location.split("?")[1] : (typeof window !== "undefined" ? window.location.search.slice(1) : "");
  const activeTab = (new URLSearchParams(query).get("tab") as TabId | null) ?? "cards";
  const profile = trpc.access.myProfile.useQuery();
  const canManage = profile.data?.permissions.includes("bot.manage") ?? false;
  const canApprove = profile.data?.permissions.includes("bot.knowledge.approve") ?? false;
  const knowledge = trpc.customerBot.knowledge.useQuery(undefined, { enabled: canManage });
  const behavior = trpc.customerBot.behaviorCards.useQuery(undefined, { enabled: canManage });
  const assets = trpc.customerBot.trainingAssets.useQuery(undefined, { enabled: canManage });
  const proposals = trpc.customerBot.learningProposals.useQuery(undefined, { enabled: canManage });
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [kind, setKind] = useState<"faq" | "policy" | "style_guidance" | "product_guidance">("style_guidance");
  const [body, setBody] = useState("");
  const utils = trpc.useUtils();
  const create = trpc.customerBot.createKnowledge.useMutation({ onSuccess: async () => { await utils.customerBot.knowledge.invalidate(); setOpen(false); setTitle(""); setBody(""); toast.success("حُفظت البطاقة كمسودة؛ لن يستخدمها البوت قبل الاعتماد."); }, onError: error => toast.error(error.message) });
  const changeStatus = trpc.customerBot.setKnowledgeStatus.useMutation({ onSuccess: async () => { await utils.customerBot.knowledge.invalidate(); toast.success("تم تحديث حالة البطاقة."); }, onError: error => toast.error(error.message) });
  const changeProposalStatus = trpc.customerBot.setLearningProposalStatus.useMutation({ onSuccess: async () => { await Promise.all([utils.customerBot.learningProposals.invalidate(), utils.customerBot.knowledge.invalidate(), utils.customerBot.behaviorCards.invalidate()]); toast.success("تم تحديث حالة المسودة."); }, onError: error => toast.error(error.message) });
  const upload = trpc.customerBot.uploadTrainingAsset.useMutation({ onSuccess: async () => { await utils.customerBot.trainingAssets.invalidate(); toast.success("قُرئ المصدر. راجعي النص قبل تحويله إلى مرشح أسلوب."); }, onError: error => toast.error(error.message) });
  const createStyle = trpc.customerBot.createStyleCandidateFromAsset.useMutation({ onSuccess: async () => { await Promise.all([utils.customerBot.knowledge.invalidate(), utils.customerBot.behaviorCards.invalidate()]); toast.success("أُنشئ مرشح لهجة كمسودة في المعرفة."); }, onError: error => toast.error(error.message) });

  function navigateTab(tab: TabId) { setLocation(`/customer-bot/learning${tab === "cards" ? "" : `?tab=${tab}`}`); }
  async function uploadFile(file: File | null) { if (!file) return; if (file.size > 16 * 1024 * 1024) { toast.error("الحد الأقصى 16 ميغابايت."); return; } const allowed = ["text/plain", "text/markdown", "application/json", "audio/mpeg", "audio/mp3", "audio/wav", "audio/x-wav", "audio/ogg", "audio/webm", "audio/mp4", "audio/m4a"]; if (!allowed.includes(file.type)) { toast.error("ارفعي TXT أو MD أو JSON أو ملفاً صوتياً مدعوماً."); return; } const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; bytes.forEach(value => { binary += String.fromCharCode(value); }); upload.mutate({ fileName: file.name, mimeType: file.type, base64: btoa(binary) }); }

  if (profile.isLoading || (canManage && (knowledge.isLoading || behavior.isLoading))) return <div className="p-8 text-sm text-muted-foreground">جارٍ تحميل المعرفة…</div>;
  if (!canManage) return <div className="p-8 text-center">لا توجد صلاحية لإدارة معرفة البوت.</div>;
  return <main dir="rtl" className="mx-auto max-w-6xl space-y-5 pb-10">
    <CustomerBotNav title="المعرفة والتعلم" description="المكان الموحد لتغذية البوت: أضيفي بطاقة بسيطة، استخدمي مساعد التعليم، راجعي السلوك والمصادر، ثم اعتمدي المسودات بعد الاختبار." action={<Button onClick={() => { setOpen(true); navigateTab("cards"); }} className="rounded-xl bg-[#1d5a4d] hover:bg-[#153f36]"><Plus className="ml-2 h-4 w-4" />بطاقة معرفة جديدة</Button>} />
    <SafetyNotice />
    <nav aria-label="أدوات المعرفة والتعلم" className="grid gap-2 rounded-2xl border border-[#e2e8e3] bg-white p-2 shadow-[0_8px_20px_rgba(41,63,53,0.04)] sm:grid-cols-3 lg:grid-cols-5">{tabs.map(tab => { const Icon = tab.icon; const active = activeTab === tab.id; return <Button key={tab.id} type="button" variant={active ? "default" : "ghost"} onClick={() => navigateTab(tab.id)} className={`h-auto justify-start rounded-xl px-3 py-3 text-right ${active ? "bg-[#1d5a4d] text-white hover:bg-[#153f36]" : "text-[#52675a] hover:bg-[#f3f8f4]"}`}><Icon className="ml-2 h-4 w-4 shrink-0" /><span><span className="block text-xs font-bold">{tab.label}</span><span className={`mt-0.5 block text-[10px] ${active ? "text-white/75" : "text-[#849189]"}`}>{tab.id === "cards" ? "المعلومات الثابتة" : tab.id === "assistant" ? "كتابة أو صوت أو قالب" : tab.id === "behavior" ? "لهجة وأمثلة وحواجز" : tab.id === "sources" ? "ملفات الفريق" : "اعتماد ومراجعة"}</span></span></Button>; })}</nav>
    {activeTab === "cards" ? <KnowledgePanel knowledge={knowledge.data ?? []} canApprove={canApprove} changeStatus={changeStatus} /> : null}
    {activeTab === "assistant" ? <CustomerBotCommandAssistant embedded /> : null}
    {activeTab === "behavior" ? <BehaviorPanel behavior={behavior.data ?? []} /> : null}
    {activeTab === "sources" ? <SourcesPanel assets={assets.data ?? []} upload={upload} createStyle={createStyle} uploadFile={uploadFile} /> : null}
    {activeTab === "drafts" ? <DraftsPanel proposals={proposals.data ?? []} canApprove={canApprove} changeProposalStatus={changeProposalStatus} /> : null}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>بطاقة معرفة مسودة</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>العنوان</Label><Input value={title} onChange={event => setTitle(event.target.value)} className="mt-2" /></div><div><Label>نوع البطاقة</Label><Select value={kind} onValueChange={value => setKind(value as typeof kind)}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="style_guidance">إرشاد أسلوب</SelectItem><SelectItem value="policy">سياسة ثابتة</SelectItem><SelectItem value="faq">إجابة شائعة</SelectItem><SelectItem value="product_guidance">إرشاد منتج</SelectItem></SelectContent></Select><p className="mt-1 text-[11px] text-[#7d8a81]">هذه البطاقة البسيطة لا تعرض تصنيفات إجراءات البيع والاختبارات؛ استخدمي مساعد التعليم لها.</p></div><div><Label>النص</Label><Textarea value={body} onChange={event => setBody(event.target.value)} className="mt-2 min-h-36" placeholder="اكتبي سياسة أو معلومة ثابتة… لا تضعي سعراً أو مخزوناً أو حالة طلب." /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>إلغاء</Button><Button disabled={!title.trim() || !body.trim() || create.isPending} onClick={() => create.mutate({ title, kind, body })} className="bg-[#1d5a4d] hover:bg-[#153f36]">حفظ مسودة</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}

function KnowledgePanel({ knowledge, canApprove, changeStatus }: { knowledge: any[]; canApprove: boolean; changeStatus: any }) { return <Panel title="بطاقات RAG والمعرفة" subtitle="تدخل الرد فقط عند اعتمادها. السعر والمخزون وحالة الطلب تبقى دائماً من بيانات المنصة الحية."><div className="space-y-3">{knowledge.length ? knowledge.map(article => <div key={article.id} className="rounded-xl border border-[#e8ece8] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold text-[#354b40]">{article.title}</h3><p className="mt-1 text-[11px] text-[#7f8b84]">{article.kind === "style_guidance" ? "إرشاد أسلوب" : article.kind === "policy" ? "سياسة" : article.kind === "product_guidance" ? "إرشاد منتج" : "إجابة شائعة"}</p></div><Badge className={statusStyle[article.status]}>{statusLabel[article.status]}</Badge></div><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm leading-6 text-[#617269]">{article.body}</p><div className="mt-3 flex gap-2">{article.status === "draft" && canApprove ? <Button size="sm" onClick={() => changeStatus.mutate({ articleId: article.id, status: "approved" })} disabled={changeStatus.isPending} className="h-8 rounded-lg bg-[#1d5a4d] text-xs hover:bg-[#153f36]"><CheckCircle2 className="ml-1 h-3.5 w-3.5" />اعتماد</Button> : null}{article.status !== "archived" ? <Button size="sm" variant="outline" onClick={() => changeStatus.mutate({ articleId: article.id, status: "archived" })} disabled={changeStatus.isPending} className="h-8 rounded-lg text-xs">أرشفة</Button> : null}</div></div>) : <Empty text="لا توجد بطاقات بعد. أضيفي سياسة أو إرشاداً ثابتاً ثم اختبريه قبل الاعتماد." />}</div></Panel>; }
function BehaviorPanel({ behavior }: { behavior: any[] }) { return <Panel title="بطاقات السلوك واللهجة" subtitle="هنا تظهر قواعد الكلام وأمثلة الرد والحواجز المعتمدة أو المسودة. لا تتحول إلى أسعار أو مخزون."><div className="space-y-3">{behavior.length ? behavior.map(card => <div key={card.id} className="rounded-xl border border-[#e8ece8] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-[#354b40]">{card.title}</h3><p className="mt-1 text-xs text-[#718077]">{card.kind === "dialect" ? "لهجة" : card.kind === "guardrail" ? "حاجز" : card.kind === "welcome" ? "ترحيب" : "مثال رد"}</p></div><Badge className={statusStyle[card.status]}>{statusLabel[card.status]}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#617269]">{card.body}</p></div>) : <Empty text="ستظهر هنا التعديلات المعتمدة من المختبر أو مساعد التعليم." />}</div></Panel>; }
function SourcesPanel({ assets, upload, createStyle, uploadFile }: { assets: any[]; upload: any; createStyle: any; uploadFile: (file: File | null) => Promise<void> }) { return <section className="rounded-2xl border border-[#e2e8e3] bg-white p-5 shadow-[0_10px_24px_rgba(41,63,53,0.05)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="flex items-center gap-2 font-bold text-[#30473d]"><UploadCloud className="h-5 w-5 text-[#a35d1e]" />مصادر تدريب الفريق</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[#74817a]">ارفعي نصاً منقحاً أو تسجيلاً صوتياً. يحول النظام الصوت إلى نص، ثم تراجعينه قبل إنشاء مرشح مسودة. لا يتعلم البوت مباشرة من الملف.</p></div><label className="inline-flex h-9 cursor-pointer items-center justify-center rounded-xl bg-[#1d5a4d] px-3 text-xs font-medium text-white hover:bg-[#153f36]"><input type="file" className="sr-only" accept=".txt,.md,.json,audio/mpeg,audio/mp3,audio/wav,audio/x-wav,audio/ogg,audio/webm,audio/mp4,audio/m4a" onChange={event => void uploadFile(event.target.files?.[0] ?? null)} disabled={upload.isPending} />{upload.isPending ? "جارٍ القراءة…" : "رفع مصدر"}</label></div><p className="mt-3 rounded-xl bg-[#fffaf2] px-3 py-2 text-xs text-[#8b6a35]">الحد الأقصى 16 ميغابايت. لا ترفعي معلومات زبائن حساسة لا تحتاجينها لتعليم الأسلوب.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{assets.map(asset => <div key={asset.id} className="rounded-xl border border-[#e8ece8] p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2">{asset.kind === "audio" ? <FileAudio className="h-4 w-4 text-[#7048a5]" /> : <FileText className="h-4 w-4 text-[#406a95]" />}<p className="truncate text-sm font-bold text-[#40584a]">{asset.originalFileName}</p></div><Badge className={asset.status === "ready" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}>{asset.status === "ready" ? "جاهز" : "تعذر"}</Badge></div>{asset.transcript ? <p className="mt-3 line-clamp-4 whitespace-pre-wrap text-xs leading-5 text-[#718077]">{asset.transcript}</p> : <p className="mt-3 text-xs text-rose-700">{asset.errorSummary || "لا يتوفر نص للمراجعة."}</p>}{asset.status === "ready" && asset.transcript ? <Button size="sm" variant="outline" className="mt-3 h-8 rounded-lg text-xs" onClick={() => createStyle.mutate({ assetId: asset.id })} disabled={createStyle.isPending}>إنشاء مرشح لهجة</Button> : null}</div>)}</div></section>; }
function DraftsPanel({ proposals, canApprove, changeProposalStatus }: { proposals: any[]; canApprove: boolean; changeProposalStatus: any }) { return <Panel title="المسودات والمراجعة" subtitle="كل ما ينشئه مساعد التعليم أو مختبر المحادثة يبقى هنا إلى أن يراجعه صاحب الصلاحية."><div className="space-y-3">{proposals.length ? proposals.map(proposal => <div key={proposal.id} className="rounded-xl border border-[#e8ece8] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold text-[#354b40]">{proposal.title}</h3><p className="mt-1 text-[11px] text-[#7f8b84]">{categoryLabel[proposal.category] || proposal.category}</p></div><Badge className={statusStyle[proposal.status]}>{statusLabel[proposal.status] || proposal.status}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#617269]">{proposal.body || proposal.editedReply}</p>{proposal.status === "draft" ? <div className="mt-3 flex gap-2"><Button size="sm" disabled={!canApprove || changeProposalStatus.isPending} onClick={() => changeProposalStatus.mutate({ proposalId: proposal.id, status: "approved" })} className="h-8 rounded-lg bg-[#1d5a4d] text-xs hover:bg-[#153f36]">اعتماد</Button><Button size="sm" variant="outline" disabled={changeProposalStatus.isPending} onClick={() => changeProposalStatus.mutate({ proposalId: proposal.id, status: "rejected" })} className="h-8 rounded-lg text-xs">رفض</Button></div> : null}</div>) : <Empty text="لا توجد مسودات معلقة. أنشئي بطاقة أو استخدمي مساعد التعليم للبدء." />}</div></Panel>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#e2e8e3] bg-white p-5 shadow-[0_10px_24px_rgba(41,63,53,0.05)]"><h2 className="flex items-center gap-2 font-bold text-[#1d5a4d]"><BookOpenText className="h-5 w-5" />{title}</h2><p className="mt-1 text-sm leading-6 text-[#74817a]">{subtitle}</p><div className="mt-4">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed bg-[#fafcf9] p-5 text-center text-xs leading-6 text-[#7b8981]"><ShieldCheck className="mx-auto mb-2 h-5 w-5 text-[#9ab0a1]" />{text}</div>; }
