import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CustomerBotNav, SafetyNotice } from "@/components/customerBot/CustomerBotNav";
import { trpc } from "@/lib/trpc";
import { Archive, CheckCircle2, ClipboardCheck, FileCheck2, ListChecks, Loader2, ShieldAlert, XCircle } from "lucide-react";
import { toast } from "sonner";

const category: Record<string, string> = { dialect_style: "لهجة ونبرة", reply_example: "مثال رد", knowledge: "بطاقة معرفة", sales_playbook: "إجراء بيع", test_case: "حالة اختبار", guardrail: "حاجز أمان", knowledge_gap: "فجوة معرفة" };
const status: Record<string, string> = { draft: "مسودة", approved: "معتمدة", rejected: "مرفوضة", archived: "مؤرشفة" };

export default function CustomerBotTesting() {
  const profile = trpc.access.myProfile.useQuery();
  const canManage = profile.data?.permissions.includes("bot.manage") ?? false;
  const canApprove = profile.data?.permissions.includes("bot.knowledge.approve") ?? false;
  const proposals = trpc.customerBot.learningProposals.useQuery(undefined, { enabled: canManage });
  const playbooks = trpc.customerBot.playbooks.useQuery(undefined, { enabled: canManage });
  const tests = trpc.customerBot.testCases.useQuery(undefined, { enabled: canManage });
  const utils = trpc.useUtils();
  const update = trpc.customerBot.setLearningProposalStatus.useMutation({ onSuccess: async () => { await Promise.all([utils.customerBot.learningProposals.invalidate(), utils.customerBot.behaviorCards.invalidate(), utils.customerBot.playbooks.invalidate(), utils.customerBot.testCases.invalidate(), utils.customerBot.knowledge.invalidate()]); toast.success("تمت مراجعة المسودة. أي أثر ناتج بقي مسودة في قسمه حتى اعتماد لاحق."); }, onError: error => toast.error(error.message) });
  if (profile.isLoading || (canManage && proposals.isLoading)) return <div className="p-8 text-sm text-muted-foreground">جارٍ تحميل المسودات…</div>;
  if (!canManage) return <div className="p-8 text-center">لا توجد صلاحية لمراجعة المسودات.</div>;
  return <main dir="rtl" className="mx-auto max-w-6xl space-y-5 pb-10">
    <CustomerBotNav title="الاختبارات والمسودات" description="راجعي التغييرات قبل أن يصبح أي منها متاحاً للبوت. الاعتماد هنا ينشئ بطاقة أو إجراءً مسوداً، وليس نشرًا صامتاً إلى الرد المباشر." />
    <SafetyNotice />
    <section className="rounded-2xl border border-[#e2e8e3] bg-white p-5 shadow-[0_10px_24px_rgba(41,63,53,0.05)]"><div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold text-[#31483d]"><ClipboardCheck className="h-5 w-5 text-[#1d5a4d]" />اقتراحات التعلم</h2><p className="mt-1 text-sm text-[#74817a]">تأتي من تعديل رد في المختبر أو من مساعد الأوامر. ارفضي ما لا تريدينه، أو اعتمديه لإنشاء مسودة في المكان الصحيح.</p></div><Badge className="bg-[#eff6f0] text-[#40624c]">{proposals.data?.filter(item => item.status === "draft").length ?? 0} قيد المراجعة</Badge></div><div className="mt-5 space-y-3">{proposals.data?.length ? proposals.data.map(item => <article key={item.id} className="rounded-xl border border-[#e7ece7] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-[#354d40]">{item.title}</h3><Badge className="bg-[#eff5f0] text-[#4c6556]">{category[item.category]}</Badge><Badge className={item.status === "draft" ? "bg-amber-50 text-amber-800" : item.status === "approved" ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-700"}>{status[item.status]}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#617269]">{item.body}</p>{item.originalReply && item.editedReply ? <details className="mt-3 text-xs text-[#6b7d72]"><summary className="cursor-pointer font-bold">عرض الفرق بين الرد الأصلي والمعدل</summary><div className="mt-2 grid gap-2 sm:grid-cols-2"><p className="rounded-lg bg-[#fafafa] p-2 leading-5">الأصلي: {item.originalReply}</p><p className="rounded-lg bg-[#f2f8f3] p-2 leading-5">المعدل: {item.editedReply}</p></div></details> : null}</div>{item.status === "draft" ? <div className="flex shrink-0 flex-wrap gap-2">{canApprove ? <Button size="sm" disabled={update.isPending} onClick={() => update.mutate({ proposalId: item.id, status: "approved" })} className="rounded-lg bg-[#1d5a4d] text-xs hover:bg-[#153f36]"><CheckCircle2 className="ml-1 h-3.5 w-3.5" />اعتماد المسودة</Button> : null}<Button size="sm" variant="outline" disabled={update.isPending} onClick={() => update.mutate({ proposalId: item.id, status: "rejected" })} className="rounded-lg text-xs"><XCircle className="ml-1 h-3.5 w-3.5" />رفض</Button><Button size="sm" variant="ghost" disabled={update.isPending} onClick={() => update.mutate({ proposalId: item.id, status: "archived" })} className="rounded-lg text-xs"><Archive className="ml-1 h-3.5 w-3.5" />أرشفة</Button></div> : null}</div></article>) : <Empty text="لا توجد اقتراحات. ابدئي من مختبر المحادثة أو مساعد الأوامر." />}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><ResourceList icon={<ListChecks className="h-5 w-5 text-[#7048a5]" />} title="إجراءات البيع" description="تظهر هنا الإجراءات المنشأة من مسودات معتمدة. تبقى منفصلة عن إعدادات التشغيل حتى يمكن مراجعتها واختبارها." items={playbooks.data?.map(item => ({ id: item.id, title: item.title, status: item.status, body: JSON.stringify(JSON.parse(item.stepsJson), null, 2) })) ?? []} empty="لا توجد إجراءات بيع بعد." /><ResourceList icon={<FileCheck2 className="h-5 w-5 text-[#406a95]" />} title="حالات الاختبار" description="تحول الحالات المهمة إلى اختبارات قابلة لإعادة التشغيل قبل توسيع Pilot أو الرد المباشر." items={tests.data?.map(item => ({ id: item.id, title: item.title, status: item.status, body: item.inputJson })) ?? []} empty="لا توجد حالات اختبار محفوظة بعد." /></section>
    <section className="rounded-2xl border border-[#f1dfc7] bg-[#fffaf4] p-4 text-sm leading-6 text-[#805f34]"><p className="flex items-center gap-2 font-bold"><ShieldAlert className="h-4 w-4" />حدود النشر</p><p className="mt-1">هذه الصفحة لا تفعّل الرد المباشر. بعد مراجعة البطاقات والإجراءات والاختبارات، يتم تشغيل Pilot من إعدادات التشغيل وعلى قناة محددة فقط.</p></section>
  </main>;
}
function ResourceList({ icon, title, description, items, empty }: { icon: React.ReactNode; title: string; description: string; items: Array<{ id: number; title: string; status: string; body: string }>; empty: string }) { return <section className="rounded-2xl border border-[#e2e8e3] bg-white p-5 shadow-[0_10px_24px_rgba(41,63,53,0.05)]"><h2 className="flex items-center gap-2 font-bold text-[#31483d]">{icon}{title}</h2><p className="mt-1 text-sm leading-6 text-[#74817a]">{description}</p><div className="mt-4 space-y-3">{items.length ? items.map(item => <div key={item.id} className="rounded-xl border border-[#e8ece8] p-3"><div className="flex items-start justify-between gap-2"><p className="font-bold text-[#40584a]">{item.title}</p><Badge className={item.status === "draft" ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}>{item.status === "draft" ? "مسودة" : "معتمدة"}</Badge></div><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap rounded-lg bg-[#fafcf9] p-2 text-[11px] leading-5 text-[#74817a]">{item.body}</pre></div>) : <Empty text={empty} />}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed bg-[#fafcf9] p-6 text-center text-xs text-[#7d8b82]">{text}</div>; }
