import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Bot, BrainCircuit, CircleAlert, Gauge, LoaderCircle, Save, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Form = { enabled: boolean; fastModel: string; escalationModel: string; minimumConfidence: number; maxDailyReplies: number; maxDailyEscalations: number };

const base: Form = { enabled: false, fastModel: "gpt-5-mini", escalationModel: "gpt-5", minimumConfidence: 75, maxDailyReplies: 100, maxDailyEscalations: 15 };

export default function CustomerBot() {
  const profile = trpc.access.myProfile.useQuery();
  const canManage = profile.data?.permissions.includes("bot.manage") ?? false;
  const settings = trpc.customerBot.settings.useQuery(undefined, { enabled: canManage });
  const models = trpc.customerBot.availableModels.useQuery(undefined, { enabled: canManage });
  const [form, setForm] = useState<Form>(base);
  useEffect(() => { if (settings.data) setForm({ enabled: settings.data.enabled, fastModel: settings.data.fastModel, escalationModel: settings.data.escalationModel, minimumConfidence: settings.data.minimumConfidence, maxDailyReplies: settings.data.maxDailyReplies, maxDailyEscalations: settings.data.maxDailyEscalations }); }, [settings.data]);
  const save = trpc.customerBot.updateSettings.useMutation({ onSuccess: async () => { await settings.refetch(); toast.success("تم حفظ إعدادات البوت. يبقى الإرسال الخارجي غير مفعّل."); }, onError: error => toast.error(error.message) });
  const availableModels = Array.from(new Set(["gpt-5-mini", "gpt-5", ...(models.data ?? [])]));
  if (profile.isLoading || settings.isLoading) return <BotSkeleton />;
  if (!canManage) return <BotForbidden />;
  return <div dir="rtl" className="mx-auto max-w-6xl space-y-5 pb-10">
    <header className="overflow-hidden rounded-[1.8rem] border border-[#e4dfd1] bg-[radial-gradient(circle_at_90%_8%,#f4e8cd,transparent_35%),linear-gradient(135deg,#fffdf9,#f6f8f3)] px-5 py-6 shadow-[0_10px_28px_rgba(41,63,53,0.06)] sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold tracking-[0.13em] text-[#9a7b3e]">HYBRID CUSTOMER ASSISTANT</p><h1 className="mt-1.5 flex items-center gap-2 text-2xl font-bold text-[#233a33]"><Bot className="h-6 w-6 text-[#1d5a4d]" />مركز بوت العملاء</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6d7a72]">ردود مقترحة من بيانات المتجر الحية، مع تصعيد مضبوط للحالات المركبة وتحويل بشري للحالات الحساسة.</p></div><Badge className={`h-fit rounded-full px-3 py-1.5 ${form.enabled ? "bg-[#e7f4ee] text-[#1d5a4d]" : "bg-[#f2efe8] text-[#6f786f]"}`}>{form.enabled ? "المسودات مفعلة" : "المسودات متوقفة"}</Badge></div></header>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-2xl border border-[#e7e1d5] bg-white p-5 shadow-[0_10px_25px_rgba(40,61,51,0.05)] sm:p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#edf5f1] p-2.5 text-[#1d5a4d]"><Sparkles className="h-5 w-5" /></div><div><h2 className="font-bold text-[#30473d]">وضع التشغيل الآمن</h2><p className="mt-1 text-xs leading-5 text-[#74817a]">التفعيل يسمح بإنشاء **مسودات** من Inbox عند طلب الموظف. لا يرسل النظام رسالة إلى WhatsApp أو أي قناة خارجية.</p></div></div><div className="mt-5 flex items-center justify-between rounded-xl border border-[#dde6df] bg-[#fbfdfb] p-4"><div><Label htmlFor="bot-enabled" className="font-bold text-[#385046]">تفعيل إنشاء المسودات</Label><p className="mt-1 text-xs text-[#7b8981]">يبقى الإرسال الآلي غير متاح حتى ربط قناة رسمية واختبارها.</p></div><Switch id="bot-enabled" checked={form.enabled} onCheckedChange={enabled => setForm(current => ({ ...current, enabled }))} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><ModelField label="نموذج المسار السريع" value={form.fastModel} onChange={fastModel => setForm(current => ({ ...current, fastModel }))} models={availableModels} help="للأسعار والألوان والتوفر والأسئلة المباشرة." /><ModelField label="نموذج التصعيد" value={form.escalationModel} onChange={escalationModel => setForm(current => ({ ...current, escalationModel }))} models={availableModels} help="للمقارنات والسياق المركب فقط." /></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><NumberField label="حد الثقة" value={form.minimumConfidence} min={1} max={100} suffix="%" onChange={minimumConfidence => setForm(current => ({ ...current, minimumConfidence }))} /><NumberField label="حد المسودات اليومي" value={form.maxDailyReplies} min={1} max={1000} onChange={maxDailyReplies => setForm(current => ({ ...current, maxDailyReplies }))} /><NumberField label="حد التصعيد اليومي" value={form.maxDailyEscalations} min={1} max={500} onChange={maxDailyEscalations => setForm(current => ({ ...current, maxDailyEscalations }))} /></div><div className="mt-6 flex justify-end"><Button disabled={save.isPending} onClick={() => save.mutate({ ...form, mode: "draft_only" })} className="rounded-xl bg-[#1d5a4d] hover:bg-[#153f36]"><Save className="ml-2 h-4 w-4" />{save.isPending ? "جارٍ الحفظ…" : "حفظ الإعدادات"}</Button></div></section>
      <aside className="space-y-4"><InfoCard icon={<Gauge />} title="كيف يقرر المسار؟" body="يجيب GPT-5 mini عن السؤال المباشر بعد قراءة حقائق حية مقيدة. لا يخمّن عندما لا يجد منتجاً أو لوناً أو سعراً مطابقاً." /><InfoCard icon={<BrainCircuit />} title="متى يتصعّد؟" body="عند مقارنة عدة موديلات أو شروط ذوقية متعددة أو استمرار حوار بلا حل أو انخفاض الثقة. المسار الافتراضي للتصعيد هو GPT-5." /><InfoCard icon={<ShieldCheck />} title="ما الذي لا يفعله؟" body="لا يغير سعراً أو مخزوناً أو طلباً، ولا يمنح خصماً، ولا يعرض بيانات عميلة أخرى. هذه الحالات تذهب مباشرةً إلى موظف مخول." /><div className="rounded-2xl border border-[#efdfb6] bg-[#fff9eb] p-4"><p className="flex items-center gap-2 text-sm font-bold text-[#805d1f]"><CircleAlert className="h-4 w-4" />قبل ربط WhatsApp</p><p className="mt-2 text-xs leading-5 text-[#8a6a35]">اختبري المسودات على سجلات Inbox الداخلية أولاً. تحفظ كل نتيجة ومسار وثقة في سجل مراجعة، ولا يحدث إرسال فعلي في هذه الدفعة.</p></div></aside>
    </div>
  </div>;
}

function ModelField({ label, value, onChange, models, help }: { label: string; value: string; onChange: (value: string) => void; models: string[]; help: string }) { return <label className="block"><span className="text-xs font-bold text-[#4e6359]">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="mt-2 h-10 rounded-xl border-[#d9d3c6]"><SelectValue /></SelectTrigger><SelectContent dir="rtl">{models.map(model => <SelectItem key={model} value={model}>{model}</SelectItem>)}</SelectContent></Select><span className="mt-1.5 block text-[11px] leading-4 text-[#849188]">{help}</span></label>; }
function NumberField({ label, value, onChange, min, max, suffix }: { label: string; value: number; onChange: (value: number) => void; min: number; max: number; suffix?: string }) { return <label className="block"><span className="text-xs font-bold text-[#4e6359]">{label}</span><div className="relative"><Input className="mt-2 h-10 rounded-xl border-[#d9d3c6] pl-8" type="number" min={min} max={max} value={value} onChange={event => onChange(Math.min(max, Math.max(min, Number(event.target.value) || min)))} />{suffix && <span className="absolute bottom-2.5 left-3 text-xs text-[#78867d]">{suffix}</span>}</div></label>; }
function InfoCard({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <section className="rounded-2xl border border-[#e7e1d5] bg-white p-4 shadow-[0_8px_20px_rgba(40,61,51,0.04)]"><div className="flex items-center gap-2 text-[#1d5a4d]"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span><h2 className="text-sm font-bold">{title}</h2></div><p className="mt-2 text-xs leading-5 text-[#718077]">{body}</p></section>; }
function BotSkeleton() { return <div className="mx-auto max-w-6xl space-y-5"><div className="h-36 animate-pulse rounded-[1.8rem] bg-[#f5f3ed]" /><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="h-[430px] animate-pulse rounded-2xl bg-[#f5f3ed]" /><div className="h-[430px] animate-pulse rounded-2xl bg-[#f5f3ed]" /></div></div>; }
function BotForbidden() { return <div dir="rtl" className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center rounded-[2rem] border border-[#e4dfd1] bg-white p-8 text-center shadow-[0_10px_28px_rgba(41,63,53,0.06)]"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff3eb] text-[#a45a32]"><ShieldCheck className="h-7 w-7" /></div><h1 className="mt-5 text-xl font-bold text-[#344840]">لا تملكين صلاحية إدارة البوت</h1><p className="mt-2 text-sm leading-6 text-[#718077]">يستطيع مدير المتجر منح تصريح «إدارة إعدادات وحدود بوت العملاء» من صفحة الصلاحيات.</p></div>; }
