import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, CircleAlert, ClipboardCheck, FileClock, Gauge, LoaderCircle, Settings2, ShieldCheck, Sparkles, UserRoundCheck, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type SettingsForm = { enabled: boolean; fastModel: string; escalationModel: string; minimumConfidence: number; maxDailyCommands: number; maxDailyEscalations: number };
type Decision = "approved" | "rejected" | "needs_clarification";
type Command = { id: number; rawCommand: string; intent: string; status: string; targetLabel: string | null; proposedChanges: string; confidence: number | null; model: string | null; escalationReason: string | null; createdAt: Date; review: { decision: string; note: string | null; executionError: string | null } | null; sources: Array<{ sourceType: string; snapshot: string }> };

const defaults: SettingsForm = { enabled: false, fastModel: "gpt-5-mini", escalationModel: "gpt-5", minimumConfidence: 75, maxDailyCommands: 60, maxDailyEscalations: 12 };
const statusMeta: Record<string, { label: string; className: string }> = { needs_review: { label: "بانتظار المراجعة", className: "bg-amber-50 text-amber-800" }, needs_clarification: { label: "يحتاج استيضاحاً", className: "bg-sky-50 text-sky-800" }, approved: { label: "معتمد", className: "bg-emerald-50 text-emerald-800" }, rejected: { label: "مرفوض", className: "bg-rose-50 text-rose-800" }, executed: { label: "نُفّذ بعد المراجعة", className: "bg-emerald-100 text-emerald-900" }, execution_failed: { label: "تعذر التنفيذ", className: "bg-red-50 text-red-800" }, expired: { label: "منتهٍ", className: "bg-slate-100 text-slate-700" } };
const intentMeta: Record<string, string> = { inventory_set: "تحديث كمية لون", selling_price_set: "تحديث سعر بيع", order_status_transition: "تغيير حالة طلب", clarification: "استيضاح", unsupported: "خارج النطاق" };

function parseChanges(value: string) { try { return JSON.parse(value) as Record<string, string | number | null>; } catch { return {}; } }
function sourceText(value: string) { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }

export default function EmployeeBot() {
  const profile = trpc.access.myProfile.useQuery();
  const canUse = profile.data?.permissions.includes("employee_bot.use") ?? false;
  const canReview = profile.data?.permissions.includes("employee_bot.review") ?? false;
  const canManage = profile.data?.permissions.includes("employee_bot.manage") ?? false;
  const settings = trpc.employeeBot.settings.useQuery(undefined, { enabled: canManage });
  const models = trpc.employeeBot.availableModels.useQuery(undefined, { enabled: canManage });
  const myCommands = trpc.employeeBot.myCommands.useQuery(undefined, { enabled: canUse });
  const queue = trpc.employeeBot.reviewQueue.useQuery({ status: "needs_review" }, { enabled: canReview });
  const summary = trpc.employeeBot.summary.useQuery(undefined, { enabled: canReview });
  const utils = trpc.useUtils();
  const [form, setForm] = useState<SettingsForm>(defaults);
  const [rawCommand, setRawCommand] = useState("");
  const [reviewing, setReviewing] = useState<Command | null>(null);
  const [decision, setDecision] = useState<Decision>("approved");
  const [note, setNote] = useState("");
  const [finalChanges, setFinalChanges] = useState<Record<string, string | number | null>>({});
  useEffect(() => { if (settings.data) setForm({ enabled: settings.data.enabled, fastModel: settings.data.fastModel, escalationModel: settings.data.escalationModel, minimumConfidence: settings.data.minimumConfidence, maxDailyCommands: settings.data.maxDailyCommands, maxDailyEscalations: settings.data.maxDailyEscalations }); }, [settings.data]);
  const availableModels = useMemo(() => Array.from(new Set(["gpt-5-mini", "gpt-5", ...(models.data ?? [])])), [models.data]);
  const refresh = async () => { await Promise.all([utils.employeeBot.myCommands.invalidate(), utils.employeeBot.reviewQueue.invalidate(), utils.employeeBot.summary.invalidate()]); };
  const create = trpc.employeeBot.createCommand.useMutation({ onSuccess: async command => { setRawCommand(""); await refresh(); toast.success(command.status === "needs_review" ? "أُنشئت المسودة للمراجعة؛ لم يتغير أي سجل بعد." : "المسودة تحتاج استيضاحاً قبل المراجعة."); }, onError: error => toast.error(error.message) });
  const saveSettings = trpc.employeeBot.updateSettings.useMutation({ onSuccess: async () => { await settings.refetch(); toast.success("تم حفظ إعدادات مساعد الموظفين؛ لا يزال التنفيذ يمر بالمراجعة."); }, onError: error => toast.error(error.message) });
  const review = trpc.employeeBot.review.useMutation({ onSuccess: async command => { setReviewing(null); await refresh(); toast.success(command.status === "executed" ? "تم التنفيذ بعد المراجعة وإعادة التحقق." : command.status === "execution_failed" ? "حُفظت المراجعة لكن تعذر التنفيذ؛ راجعي السبب." : "حُفظ قرار المراجعة من دون تنفيذ."); }, onError: error => toast.error(error.message) });
  function openReview(command: Command) { setReviewing(command); setDecision(command.status === "needs_clarification" ? "needs_clarification" : "approved"); setNote(""); setFinalChanges(parseChanges(command.proposedChanges)); }
  function saveReview() { if (!reviewing) return; review.mutate({ commandId: reviewing.id, decision, note: note.trim() || null, finalChanges: decision === "approved" ? finalChanges : null }); }
  if (profile.isLoading) return <Skeleton />;
  if (!canUse && !canReview && !canManage) return <Forbidden />;
  const metrics = summary.data ?? { total: 0, needsReview: 0, needsClarification: 0, executed: 0, failed: 0 };
  return <div dir="rtl" className="mx-auto max-w-6xl space-y-5 pb-10">
    <header className="overflow-hidden rounded-[1.8rem] border border-[#e4dfd1] bg-[radial-gradient(circle_at_90%_8%,#f4e8cd,transparent_35%),linear-gradient(135deg,#fffdf9,#f6f8f3)] px-5 py-6 shadow-[0_10px_28px_rgba(41,63,53,0.06)] sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold tracking-[0.13em] text-[#9a7b3e]">EMPLOYEE OPERATIONS ASSISTANT</p><h1 className="mt-1.5 flex items-center gap-2 text-2xl font-bold text-[#233a33]"><UserRoundCheck className="h-6 w-6 text-[#1d5a4d]" />مساعد الموظفين</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6d7a72]">حوّلي أمرك إلى مسودة منظمة، ثم يراجعها موظف آخر قبل أي تغيير على كمية أو سعر أو حالة طلب.</p></div><Badge className={`h-fit rounded-full px-3 py-1.5 ${form.enabled ? "bg-[#e7f4ee] text-[#1d5a4d]" : "bg-[#f2efe8] text-[#6f786f]"}`}>{form.enabled ? "المسودات مفعلة" : "المسودات متوقفة"}</Badge></div></header>
    {canReview && <section className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric icon={<FileClock />} label="كل المسودات" value={metrics.total} /><Metric icon={<ClipboardCheck />} label="للمراجعة" value={metrics.needsReview} tone="amber" /><Metric icon={<CircleAlert />} label="تحتاج استيضاحاً" value={metrics.needsClarification} tone="blue" /><Metric icon={<CheckCircle2 />} label="نُفذت بمراجعة" value={metrics.executed} tone="green" /><Metric icon={<XCircle />} label="تعذر تنفيذها" value={metrics.failed} tone="rose" /></section>}
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-[#e7e1d5] bg-white p-5 shadow-[0_10px_25px_rgba(40,61,51,0.05)] sm:p-6"><SectionHeader icon={<Sparkles />} title="أمر جديد" description="النطاق الآمن: كمية لون كاملة، سعر بيع، أو انتقال حالة طلب مسموح. لا تستخدم الأوامر للحذف أو الخصم أو القسيمة أو تغيير المخزون تلقائياً." />{canUse ? <><Textarea value={rawCommand} onChange={event => setRawCommand(event.target.value)} className="mt-4 min-h-28 resize-y rounded-xl border-[#d9d3c6]" placeholder="مثال: اجعل كمية اللون الزيتي من HIJ-102 تساوي 8" /><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-[#78867e]">تقرأ المسودة الحقائق الموجودة في المتجر فقط، وقد تطلب استيضاحاً إذا لم تحدد المنتج أو اللون.</p><Button disabled={create.isPending || rawCommand.trim().length < 3} onClick={() => create.mutate({ rawCommand: rawCommand.trim() })} className="shrink-0 rounded-xl bg-[#1d5a4d] hover:bg-[#153f36]"><Bot className="ml-2 h-4 w-4" />{create.isPending ? "جارٍ إنشاء المسودة…" : "إنشاء مسودة"}</Button></div></> : <Empty icon={<ShieldCheck />} title="صلاحية الاستخدام غير متاحة" body="تحتاجين تصريح «استخدام مساعد الموظفين» لإنشاء مسودات، ولا يكفي تصريح المراجعة وحده." />}</div><aside className="space-y-4"><Info icon={<ShieldCheck />} title="مراجعة مستقلة" body="لا يستطيع منشئ المسودة اعتمادها أو تنفيذها بنفسه. يعتمدها موظف آخر يملك أيضاً صلاحية العملية المطلوبة." /><Info icon={<Gauge />} title="توجيه هجين" body="يفسر المسار السريع الأمر أولاً، ثم يصعّد إلى GPT-5 عند نقص الثقة أو تعدد تطابقات المنتج. يظل كل شيء مسودة." /><Info icon={<CircleAlert />} title="حدود ثابتة" body="لا حذف ولا خصومات أو قسائم أو سعر تكلفة أو إلغاء طلب. أي أمر خارج النطاق يتحول إلى استيضاح أو يرفض." /></aside></section>
    <section className="grid gap-5 xl:grid-cols-2"><CommandList title="مسوداتي" description="تتابعين مسوداتك؛ لا تظهر مسودات موظف آخر." commands={(myCommands.data ?? []) as Command[]} loading={myCommands.isLoading} action={canReview ? openReview : undefined} /><CommandList title="طابور مراجعة الفريق" description="لا تظهر هنا إلا المسودات الجاهزة لمراجع مستقل." commands={(queue.data ?? []) as Command[]} loading={queue.isLoading} action={openReview} empty="لا توجد مسودات بانتظار مراجعة." /></section>
    {canManage && <section className="rounded-2xl border border-[#e7e1d5] bg-white p-5 shadow-[0_10px_25px_rgba(40,61,51,0.05)] sm:p-6"><SectionHeader icon={<Settings2 />} title="إعدادات مساعد الموظفين" description="اختيار النموذج وحد الاستخدام يضبط إنشاء المسودات فقط؛ لا يجعل التنفيذ تلقائياً." /><div className="mt-4 flex items-center justify-between rounded-xl border border-[#dde6df] bg-[#fbfdfb] p-4"><div><Label className="font-bold text-[#385046]">تفعيل إنشاء المسودات</Label><p className="mt-1 text-xs text-[#7b8981]">يبقى كل تغيير رهناً بمراجعة موظف مستقل وإعادة تحقق من الصلاحية.</p></div><Switch checked={form.enabled} onCheckedChange={enabled => setForm(current => ({ ...current, enabled }))} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><ModelField label="المسار السريع" value={form.fastModel} models={availableModels} onChange={fastModel => setForm(current => ({ ...current, fastModel }))} /><ModelField label="مسار التصعيد" value={form.escalationModel} models={availableModels} onChange={escalationModel => setForm(current => ({ ...current, escalationModel }))} /><NumberField label="حد الثقة" value={form.minimumConfidence} suffix="%" min={1} max={100} onChange={minimumConfidence => setForm(current => ({ ...current, minimumConfidence }))} /><NumberField label="حد المسودات" value={form.maxDailyCommands} min={1} max={1000} onChange={maxDailyCommands => setForm(current => ({ ...current, maxDailyCommands }))} /><NumberField label="حد التصعيد" value={form.maxDailyEscalations} min={1} max={500} onChange={maxDailyEscalations => setForm(current => ({ ...current, maxDailyEscalations }))} /></div><div className="mt-5 flex justify-end"><Button disabled={saveSettings.isPending} onClick={() => saveSettings.mutate(form)} className="rounded-xl bg-[#1d5a4d] hover:bg-[#153f36]">{saveSettings.isPending ? "جارٍ الحفظ…" : "حفظ الإعدادات"}</Button></div></section>}
    <Dialog open={Boolean(reviewing)} onOpenChange={open => !open && setReviewing(null)}><DialogContent dir="rtl" className="max-w-2xl"><DialogHeader><DialogTitle>مراجعة مسودة الأمر</DialogTitle><DialogDescription>{reviewing?.targetLabel ?? "راجعي الحقول قبل أي تنفيذ."} — لا ينفذ الاعتماد إلا بعد التحقق من الصلاحيات وقواعد المنتج أو الطلب من جديد.</DialogDescription></DialogHeader>{reviewing && <div className="space-y-4 py-2"><div className="rounded-xl bg-[#f7faf8] p-3 text-sm text-[#52675e]"><p className="text-xs font-bold text-[#74817a]">أمر الموظف</p><p className="mt-1 whitespace-pre-wrap">{reviewing.rawCommand}</p></div><label className="block text-xs font-semibold text-[#5d6e65]"><span className="mb-1.5 block">قرار المراجعة</span><Select value={decision} onValueChange={value => setDecision(value as Decision)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent dir="rtl"><SelectItem value="approved">اعتماد وتنفيذ بعد التحقق</SelectItem><SelectItem value="needs_clarification">طلب استيضاح</SelectItem><SelectItem value="rejected">رفض المسودة</SelectItem></SelectContent></Select></label>{decision === "approved" && <FinalChanges command={reviewing} changes={finalChanges} setChanges={setFinalChanges} />}<label className="block text-xs font-semibold text-[#5d6e65]"><span className="mb-1.5 block">ملاحظة داخلية (اختيارية)</span><Textarea value={note} onChange={event => setNote(event.target.value)} className="min-h-20 resize-y" placeholder="سبب الرفض أو الاستيضاح أو ملحوظة المراجعة…" /></label><details className="rounded-xl border border-[#e8e3d8] p-3"><summary className="cursor-pointer text-xs font-bold text-[#53665d]">مصادر الحقائق المقروءة ({reviewing.sources.length})</summary><div className="mt-3 space-y-2">{reviewing.sources.map((source, index) => <pre key={index} className="overflow-x-auto rounded-lg bg-[#f8f6f1] p-2 text-[11px] text-[#697970]">{sourceText(source.snapshot)}</pre>)}</div></details></div>}<DialogFooter><Button variant="outline" onClick={() => setReviewing(null)}>إلغاء</Button><Button disabled={review.isPending} onClick={saveReview} className="bg-[#1d5a4d] hover:bg-[#153f36]">{review.isPending ? "جارٍ الحفظ…" : decision === "approved" ? "اعتماد ومتابعة التنفيذ" : "حفظ القرار"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function CommandList({ title, description, commands, loading, action, empty = "لم تُنشأ مسودات بعد." }: { title: string; description: string; commands: Command[]; loading: boolean; action?: (command: Command) => void; empty?: string }) { return <section className="rounded-2xl border border-[#e7e1d5] bg-white p-5 shadow-[0_10px_25px_rgba(40,61,51,0.05)] sm:p-6"><SectionHeader icon={<ClipboardCheck />} title={title} description={description} />{loading ? <Rows /> : commands.length ? <div className="mt-4 space-y-3">{commands.map(command => <article key={command.id} className="rounded-xl border border-[#ece6d9] bg-[#fffefd] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-[#395047]">{command.targetLabel ?? intentMeta[command.intent] ?? "أمر موظف"}</p><Badge className={statusMeta[command.status]?.className ?? "bg-slate-100 text-slate-700"}>{statusMeta[command.status]?.label ?? command.status}</Badge></div><p className="mt-1 text-xs text-[#7a8880]">{intentMeta[command.intent] ?? command.intent} · {command.model ?? "دون نموذج"}{command.confidence !== null ? ` · ثقة ${command.confidence}%` : ""}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#697a71]">{command.rawCommand}</p>{command.escalationReason && <p className="mt-2 text-xs text-[#986532]">سبب التصعيد: {command.escalationReason}</p>}{command.review?.executionError && <p className="mt-2 text-xs text-[#a34439]">سبب التعذر: {command.review.executionError}</p>}</div>{action && ["needs_review", "needs_clarification"].includes(command.status) && <Button size="sm" onClick={() => action(command)} className="h-9 shrink-0 rounded-lg bg-[#1d5a4d] text-xs hover:bg-[#153f36]"><ClipboardCheck className="ml-1.5 h-3.5 w-3.5" />مراجعة</Button>}</div></article>)}</div> : <Empty icon={<FileClock />} title="القائمة فارغة" body={empty} />}</section>; }
function FinalChanges({ command, changes, setChanges }: { command: Command; changes: Record<string, string | number | null>; setChanges: (value: Record<string, string | number | null>) => void }) { if (command.intent === "inventory_set") return <NumberField label="الكمية النهائية" value={Number(changes.inventoryQuantity ?? 0)} min={0} max={100000} onChange={inventoryQuantity => setChanges({ ...changes, inventoryQuantity })} />; if (command.intent === "selling_price_set") return <NumberField label="سعر البيع النهائي" value={Number(changes.sellingPrice ?? 0)} min={1} max={100000000} onChange={sellingPrice => setChanges({ ...changes, sellingPrice })} />; if (command.intent === "order_status_transition") return <label className="block text-xs font-semibold text-[#5d6e65]"><span className="mb-1.5 block">الحالة النهائية</span><Select value={String(changes.nextStatus ?? "confirmed")} onValueChange={nextStatus => setChanges({ ...changes, nextStatus })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent dir="rtl"><SelectItem value="needs_contact">يحتاج تواصل</SelectItem><SelectItem value="confirmed">مؤكد</SelectItem><SelectItem value="preparing">قيد التجهيز</SelectItem><SelectItem value="out_for_delivery">خرج للتوصيل</SelectItem><SelectItem value="completed">مكتمل</SelectItem></SelectContent></Select></label>; return <Empty icon={<CircleAlert />} title="لا يوجد تغيير قابل للتنفيذ" body="يمكن حفظ قرار طلب الاستيضاح أو الرفض فقط لهذه المسودة." />; }
function SectionHeader({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div><h2 className="flex items-center gap-2 font-bold text-[#30473d]"><span className="text-[#1d5a4d] [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{title}</h2><p className="mt-1.5 max-w-2xl text-xs leading-5 text-[#74817a]">{description}</p></div>; }
function Metric({ icon, label, value, tone = "slate" }: { icon: React.ReactNode; label: string; value: number; tone?: "slate" | "green" | "blue" | "rose" | "amber" }) { const colors = { slate: "bg-[#f4f3ee] text-[#65736c]", green: "bg-[#eaf5ee] text-[#24704f]", blue: "bg-[#eef5fa] text-[#3f7191]", rose: "bg-[#fff0ee] text-[#b46050]", amber: "bg-[#fff7e6] text-[#a47728]" }; return <div className="rounded-xl border border-[#e9e4d9] bg-white p-3 shadow-[0_6px_16px_rgba(40,61,51,0.035)]"><span className={`flex h-7 w-7 items-center justify-center rounded-lg ${colors[tone]} [&>svg]:h-3.5 [&>svg]:w-3.5`}>{icon}</span><p className="mt-3 text-xl font-bold text-[#344b41]">{value}</p><p className="mt-1 text-[11px] leading-4 text-[#78867e]">{label}</p></div>; }
function Info({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <section className="rounded-2xl border border-[#e7e1d5] bg-white p-4 shadow-[0_8px_20px_rgba(40,61,51,0.04)]"><div className="flex items-center gap-2 text-[#1d5a4d]"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span><h2 className="text-sm font-bold">{title}</h2></div><p className="mt-2 text-xs leading-5 text-[#718077]">{body}</p></section>; }
function Empty({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="mt-4 flex min-h-32 flex-col items-center justify-center rounded-xl border border-dashed border-[#e2ddd1] bg-[#fcfbf8] p-5 text-center"><span className="text-[#a3afa8] [&>svg]:h-7 [&>svg]:w-7">{icon}</span><p className="mt-3 text-sm font-bold text-[#5b6d64]">{title}</p><p className="mt-1 max-w-sm text-xs leading-5 text-[#849188]">{body}</p></div>; }
function Rows() { return <div className="mt-4 space-y-3">{Array.from({ length: 2 }).map((_, index) => <div key={index} className="h-24 animate-pulse rounded-xl bg-[#f6f5f0]" />)}</div>; }
function ModelField({ label, value, models, onChange }: { label: string; value: string; models: string[]; onChange: (value: string) => void }) { return <label className="block"><span className="text-xs font-bold text-[#4e6359]">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="mt-2 h-10 rounded-xl border-[#d9d3c6]"><SelectValue /></SelectTrigger><SelectContent dir="rtl">{models.map(model => <SelectItem key={model} value={model}>{model}</SelectItem>)}</SelectContent></Select></label>; }
function NumberField({ label, value, onChange, min, max, suffix }: { label: string; value: number; onChange: (value: number) => void; min: number; max: number; suffix?: string }) { return <label className="block"><span className="text-xs font-bold text-[#4e6359]">{label}</span><div className="relative"><Input className="mt-2 h-10 rounded-xl border-[#d9d3c6] pl-8" type="number" min={min} max={max} value={value} onChange={event => onChange(Math.min(max, Math.max(min, Number(event.target.value) || min)))} />{suffix && <span className="absolute bottom-2.5 left-3 text-xs text-[#78867d]">{suffix}</span>}</div></label>; }
function Skeleton() { return <div className="mx-auto max-w-6xl space-y-5"><div className="h-36 animate-pulse rounded-[1.8rem] bg-[#f5f3ed]" /><div className="h-72 animate-pulse rounded-2xl bg-[#f5f3ed]" /></div>; }
function Forbidden() { return <div dir="rtl" className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center rounded-[2rem] border border-[#e4dfd1] bg-white p-8 text-center shadow-[0_10px_28px_rgba(41,63,53,0.06)]"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff3eb] text-[#a45a32]"><ShieldCheck className="h-7 w-7" /></div><h1 className="mt-5 text-xl font-bold text-[#344840]">لا تملكين صلاحية مساعد الموظفين</h1><p className="mt-2 text-sm leading-6 text-[#718077]">يمكن لمدير المتجر منح صلاحيات الاستخدام أو المراجعة أو الإعداد من صفحة الصلاحيات.</p></div>; }
