import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("عقد بطاقات الألوان وتعديل المنتج", () => {
  it("يعرض بطاقة واحدة لكل لون ومراجعة تلقائية ومساحة تحرير منفصلة للعدد والصور", () => {
    const source = readFileSync(resolve(process.cwd(), "client/src/pages/Products.tsx"), "utf8");

    expect(source).toContain("trpc.products.mediaPreviews.useQuery");
    expect(source).toContain("<ColorCard");
    expect(source).toContain("اعتماد الاقتراحات المعدلة");
    expect(source).toContain("اعتماد هذه المجموعة");
    expect(source).toContain("حللت الصور المحددة");
    expect(source).toContain("تعديل المنتج");
    expect(source).toContain("إضافة مجموعة صور");
    expect(source).toContain("saveColorDetails");
    expect(source).toContain("حفظ</Button>");
    expect(source).not.toContain("حفظ الاسم");
    expect(source).not.toContain("حفظ العدد");
    expect(source).toContain("trpc.products.analyzeColors.useMutation");
    expect(source).toContain("trpc.products.saveColorInventory.useMutation");
    expect(source).toContain("إضافة صور");
    expect(source).not.toContain("trpc.products.saveInventory.useMutation");
    expect(source).toContain("detachMedia");
    expect(source).toContain("trpc.products.deleteColor.useMutation");
    expect(source).toContain("trpc.products.deletePermanently.useMutation");
    expect(source).toContain("toggleSuggestionMedia");
    expect(source).toContain("حذف اللون");
    expect(source).toContain("حذف المنتج نهائيًا");
    expect(source).toContain("صور غير مسندة إلى لون");
    expect(source).toContain("هل أنت متأكد من حذف المنتج؟");
    expect(source).toContain("نعم، احذف المنتج");
    expect(source).toContain("<AlertDialogCancel>لا</AlertDialogCancel>");
    expect(source).toContain("ربط أي صورة بلون");
    expect(source).toContain("إضافة اللون");
    expect(source).toContain("هل أنت متأكد من حذف اللون؟");
    expect(source).toContain("نعم، احذف اللون");
    expect(source).not.toContain("اكتب اسم اللون نفسه");
    expect(source).toContain("trpc.catalogSync.deletedProducts.useQuery");
    expect(source).toContain("trpc.catalogSync.restoreDeletedProduct.useMutation");
    expect(source).toContain("استعادة من Catalog");
    expect(source).toContain("استعادة كمسودة");
    expect(source).toContain("نعم، استعده كمسودة");
    expect(source).toContain('mediaType === "video"');
    expect(source).toContain("فيديوهات المنتج");
    expect(source).toContain("لا تدخل في تحليل الألوان");
    expect(source).toContain("فتح الفيديو الأصلي في OneDrive");
    expect(source).toContain("video.playbackReady && video.dataUrl");
    expect(source).toContain("aspect-[9/16]");
    expect(source).toContain("جاهز للمراجعة");
    expect(source).toContain("قابل للنشر بعد اعتماد آلية التفعيل");
    expect(source).toContain("غير قابل للنشر بعد");
    expect(source).not.toContain("حفظ المخزون");
  });
});
