import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("واجهة المتجر العامة", () => {
  it("تعرض المنتجات النشطة وتفاصيل اللون وسلة وملخصًا نهائيًا للطلب", () => {
    const source = readFileSync(new URL("./Storefront.tsx", import.meta.url), "utf8");
    expect(source).toContain("trpc.products.publicList.useQuery");
    expect(source).toContain("trpc.products.publicByCode.useQuery");
    expect(source).toContain("StoreProductEnhancements");
    expect(source).not.toContain("createRoot");
    expect(source).toContain("اختاري اللون");
    expect(source).toContain("أضف ");
    expect(source).toContain("تم ومتابعة الطلب");
    expect(source).toContain("سلتك");
    expect(source).toContain("governorates");
    expect(source).toContain("اختاري المحافظة");
    expect(source).toContain("border-2");
    expect(source).toContain("أجرة التوصيل");
    expect(source).toContain("الإجمالي النهائي");
    expect(source).toContain("موافق وإرسال الطلب");
    expect(source).toContain("StoreProductEnhancements {...listEnhancementProps} />{cartOpen && cartDrawer}{checkoutOpen && checkout}");
    expect(source).toContain("trpc.orders.createFromStorefront.useMutation");
    expect(source).toContain("removeCoupon");
    expect(source).toContain("setAppliedCoupon(couponCode.trim().toUpperCase())");
    expect(source).toContain("يُطبّق الكود تلقائيًا ويُحدّث الإجمالي فورًا");
    expect(source).toContain("قسيمة الخصم");
    expect(source).toContain("خصم القسيمة");
    expect(source).toContain("couponCode: appliedCoupon");
    expect(source).toContain("price(total)");
    expect(source).toContain("FreeDeliveryProgress");
    expect(source).toContain("remainingForFreeDelivery");
    expect(source).toContain("توصيل مجاني للطلبات الكبيرة");
    expect(source).toContain("freeDeliveryEnabled");
    expect(source).toContain("احتفال التوصيل المجاني");
    expect(source).toContain("celebrating");
    expect(source).toContain("معلومة عن سياسة التوصيل المجاني");
    expect(source).toContain("الخصم لا يغير هذه العتبة");
    expect(source).toContain("SuggestedProducts");
    expect(source).toContain("منتجات مقترحة للتوصيل المجاني");
    expect(source).toContain("شريط تمرير المنتجات المقترحة");
    expect(source).toContain("snap-x snap-mandatory");
    expect(source).toContain("quickAddSuggestion");
    expect(source).toContain("إضافة للسلة");
    expect(source).toContain("السعر الأصلي قبل الخصم");
    expect(source).toContain("price(subtotal + deliveryFee)");
    expect(source).toContain("LoaderCircle");
    expect(source).toContain("جارٍ التحقق من كود الخصم");
    expect(source).toContain("elegant_hijab_applied_coupon");
    expect(source).toContain("window.localStorage.setItem");
    expect(source).toContain("عرض سريع");
    expect(source).toContain("group-hover:scale-105");
    expect(source).toContain("يُطبّق الكود تلقائيًا ويُحدّث الإجمالي فورًا");
    expect(source).toContain("أضيفي ${price(remainingForFreeDelivery)} للحصول على توصيل مجاني");
    expect(source).toContain("ابحثي باسم الموديل أو الرمز");
    expect(source).toContain("فلتر السعر");
    expect(source).toContain("كل الألوان");
    expect(source).toContain("filteredProducts");
    expect(source).toContain("لا توجد منتجات مطابقة");
    expect(source).toContain("elegant_hijab_favorite_products");
    expect(source).toContain("منتجاتك المفضلة");
    expect(source).toContain("منتجات شاهدتها مؤخرًا");
    expect(source).not.toContain("setAgreed");
    expect(source).not.toContain("form.governorate ? price(deliveryFee)");
    expect(source).not.toContain("الدفع الإلكتروني");
  });
});
