export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  oneDriveClientId: process.env.MICROSOFT_ONEDRIVE_CLIENT_ID ?? "",
  oneDriveClientSecret: process.env.MICROSOFT_ONEDRIVE_CLIENT_SECRET ?? "",
  oneDriveRedirectUri: process.env.MICROSOFT_ONEDRIVE_REDIRECT_URI ?? "",
  metaAppSecret: process.env.META_APP_SECRET ?? "",
  metaAppId: process.env.META_APP_ID ?? "",
  metaRedirectUri: process.env.META_REDIRECT_URI ?? "https://eleganthijab-efpivkpx.manus.space/api/meta/oauth/callback",
  metaGraphApiVersion: process.env.META_GRAPH_API_VERSION ?? "v26.0",
  metaMessagingConfigurationId: process.env.META_CONFIG_MESSAGING_ID ?? "",
  metaContentConfigurationId: process.env.META_CONFIG_CONTENT_ID ?? "",
  metaAdsReadConfigurationId: process.env.META_CONFIG_ADS_READ_ID ?? "",
  metaLeadsConfigurationId: process.env.META_CONFIG_LEADS_ID ?? "",
  metaCatalogConfigurationId: process.env.META_CONFIG_CATALOG_ID ?? "",
  metaMeasurementConfigurationId: process.env.META_CONFIG_MEASUREMENT_ID ?? "",
  metaWebhookVerifyToken: process.env.META_WEBHOOK_VERIFY_TOKEN ?? "",
  metaGraphAccessToken: process.env.META_GRAPH_ACCESS_TOKEN ?? "",
};
