import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { skipToken } from "@tanstack/react-query";
import { CheckCircle2, CloudCog, FolderTree, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type TreeNode = {
  folderId: string;
  name: string;
  path: string;
  depth: number;
  kind: "category" | "product" | "needs_review";
  mediaFileCount: number;
  children: TreeNode[];
  warning: string | null;
};

type FolderOption = { id: string; name: string; driveId: string; webUrl: string | null };

function CatalogTreeNode({ node }: { node: TreeNode }) {
  const styles = node.kind === "product"
    ? "border-[#cce0d7] bg-[#f3faf5] text-[#245b4d]"
    : node.kind === "needs_review"
      ? "border-[#f0d6bc] bg-[#fff7ef] text-[#9c4b25]"
      : "border-[#e2e9e4] bg-white text-[#28463b]";
  const label = node.kind === "product" ? `منتج · ${node.mediaFileCount} وسائط` : node.kind === "needs_review" ? "يحتاج مراجعة" : "تصنيف";
  return <li className="space-y-2"><div className={`rounded-xl border p-3 ${styles}`}><div className="flex items-center justify-between gap-3"><span className="font-bold">{node.name}</span><span className="shrink-0 text-xs">{label}</span></div>{node.warning && <p className="mt-1 text-xs leading-5">{node.warning}</p>}</div>{node.children.length > 0 && <ul className="mr-4 space-y-2 border-r border-[#dce7df] pr-3">{node.children.map(child => <CatalogTreeNode key={child.folderId} node={child} />)}</ul>}</li>;
}

function stageLabel(stage: string | null | undefined) {
  return ({ discovering_folders: "جارٍ اكتشاف مجلدات المنتجات", reading_product: "جارٍ قراءة ملفات المنتجات", copying_operational_media: "جارٍ تجهيز النسخ التشغيلية", analyzing_colors: "جارٍ تحليل الألوان للمراجعة", processing_folders: "جارٍ تثبيت النتائج", completed: "اكتملت آخر عملية", failed: "تعذرت آخر عملية" } as Record<string, string>)[stage ?? ""] ?? "جاهز للاستيراد";
}

export function CatalogSourcePanel({ canConfigure }: { canConfigure: boolean }) {
  const utils = trpc.useUtils();
  const selection = trpc.integrations.catalogSelectionStatus.useQuery();
  const syncStatus = trpc.catalogSync.status.useQuery();
  const groups = trpc.integrations.catalogGroups.useQuery(undefined, { enabled: selection.data?.status === "catalog_selected" });
  const [treeOpen, setTreeOpen] = useState(false);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [pickerPath, setPickerPath] = useState<FolderOption[]>([]);
  const [selectedGroupId, setSelectedGroupId] = useState<string>("");
  const treePreview = trpc.integrations.previewCatalogTree.useQuery(undefined, { enabled: treeOpen && selection.data?.status === "catalog_selected" });
  const savedCategories = trpc.integrations.productCategoryTree.useQuery(undefined, { enabled: selection.data?.status === "catalog_selected" });
  const groupPreview = trpc.integrations.previewCatalogGroupProducts.useQuery(selectedGroupId ? { groupId: selectedGroupId } : skipToken, { enabled: Boolean(selectedGroupId) });
  const roots = trpc.integrations.catalogRootFolders.useQuery(undefined, { enabled: pickerOpen && selection.data?.status === "connected" });
  const active = pickerPath[pickerPath.length - 1];
  const children = trpc.integrations.catalogFolderChildren.useQuery(active ? { driveId: active.driveId, folderId: active.id } : skipToken, { enabled: pickerOpen && Boolean(active) });
  const folders = (active ? children.data : roots.data) as FolderOption[] | undefined;
  const connect = trpc.integrations.beginCatalogSelection.useMutation({ onSuccess: result => window.location.assign(result.authorizationUrl) });
  const selectRoot = trpc.integrations.selectCatalogRoot.useMutation({ onSuccess: async () => { await Promise.all([utils.integrations.catalogSelectionStatus.invalidate(), utils.integrations.catalogRootFolders.invalidate(), utils.integrations.previewCatalogTree.invalidate()]); setPickerOpen(false); setPickerPath([]); } });
  const syncTree = trpc.integrations.syncCatalogCategoryTree.useMutation({ onSuccess: async () => { await utils.integrations.productCategoryTree.invalidate(); } });
  const runImport = trpc.catalogSync.runNow.useMutation({ onSuccess: async () => { await Promise.all([utils.products.list.invalidate(), utils.catalogSync.status.invalidate(), utils.integrations.previewCatalogTree.invalidate()]); } });
  useEffect(() => { if (!syncStatus.data?.isRunning) return; const timer = window.setInterval(() => { void syncStatus.refetch(); }, 2_000); return () => window.clearInterval(timer); }, [syncStatus.data?.isRunning, syncStatus.refetch]);
  const isSelected = selection.data?.status === "catalog_selected";
  const isConnected = selection.data?.status === "connected";
  const progress = syncStatus.data?.lastRunTotalFolders ? Math.min(100, Math.round(((syncStatus.data.lastRunProcessedFolders ?? 0) / syncStatus.data.lastRunTotalFolders) * 100)) : syncStatus.data?.isRunning ? 8 : 0;
  const openPicker = () => { setPickerPath([]); setPickerOpen(true); };
  const chooseFolder = (folder: FolderOption) => selectRoot.mutate({ driveId: folder.driveId, folderId: folder.id, folderName: folder.name, folderPath: ["OneDrive", ...pickerPath.map(item => item.name), folder.name].join("/") });
  const lastSummary = useMemo(() => { try { return syncStatus.data?.lastSummary ? JSON.parse(syncStatus.data.lastSummary) as { discovered?: number; draftsCreated?: number; existing?: number; failed?: number; operationalCopiesCreated?: number } : null; } catch { return null; } }, [syncStatus.data?.lastSummary]);

  return <section className="rounded-3xl border border-[#d8e5de] bg-[#f7fbf8] p-5 shadow-[0_12px_28px_rgba(43,58,49,0.04)] sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white text-[#245b4d]"><CloudCog className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#8a6a35]">مصدر المنتجات</p><h2 className="mt-1 text-xl font-black text-[#183d35]">OneDrive داخل قسم المنتجات</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[#68756e]">من هنا تربط الجذر، تراجع الأقسام والمنتجات، ثم تبدأ استيراداً فعلياً آمناً. إعداد Microsoft السري يبقى في صفحة إعدادات OneDrive.</p></div></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-2 text-xs font-bold ${isSelected ? "bg-[#e4f3ea] text-[#17633b]" : "bg-[#fff1de] text-[#8a5a23]"}`}>{isSelected ? `الجذر: ${selection.data?.selectedFolderName ?? "محدد"}` : isConnected ? "تم التفويض؛ اختر الجذر" : "OneDrive غير مرتبط"}</span>{isSelected && <Button size="sm" variant="outline" onClick={openPicker} disabled={!canConfigure} className="border-[#b9d3c6] text-[#245b4d]"><FolderTree className="ml-1 h-4 w-4" />تغيير الجذر</Button>}{!isSelected && <Button size="sm" onClick={() => isConnected ? openPicker() : connect.mutate()} disabled={!canConfigure || connect.isPending} className="bg-[#183d35] text-white hover:bg-[#245b4d]">{connect.isPending ? "جارٍ فتح التفويض" : isConnected ? "اختيار الجذر" : "ربط OneDrive"}</Button>}</div></div>
    {selection.data?.lastError && <p className="mt-4 rounded-xl border border-[#f0d6bc] bg-[#fff7ef] p-3 text-xs leading-5 text-[#9c4b25]">{selection.data.lastError}</p>}
    {isSelected && <>
      <div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-white p-4"><p className="text-xs text-[#74817a]">الجذر المعتمد</p><p className="mt-1 truncate text-sm font-bold text-[#183d35]">{selection.data?.selectedFolderPath ?? selection.data?.selectedFolderName}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-[#74817a]">التصنيفات المحفوظة</p><p className="mt-1 text-2xl font-black text-[#a47d40]">{savedCategories.data?.length ?? 0}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-[#74817a]">حالة الاستيراد</p><p className="mt-1 text-sm font-bold text-[#245b4d]">{stageLabel(syncStatus.data?.lastRunStage)}</p></div></div>
      <div className="mt-5 flex flex-wrap items-center gap-2"><Button onClick={() => setTreeOpen(value => !value)} variant="outline" className="border-[#b9d3c6] text-[#245b4d]"><FolderTree className="ml-1.5 h-4 w-4" />{treeOpen ? "إخفاء الشجرة" : "معاينة الشجرة والأقسام"}</Button><Button onClick={() => runImport.mutate()} disabled={!canConfigure || runImport.isPending || syncStatus.data?.isRunning} className="bg-[#183d35] text-white hover:bg-[#245b4d]"><RefreshCw className={`ml-1.5 h-4 w-4 ${(runImport.isPending || syncStatus.data?.isRunning) ? "animate-spin" : ""}`} />{syncStatus.data?.isRunning ? "جارٍ استيراد المنتجات" : "استيراد/تحديث من OneDrive"}</Button></div>
      {(syncStatus.data?.isRunning || syncStatus.data?.lastRunStage === "failed" || lastSummary) && <div className={`mt-4 rounded-2xl border p-4 ${syncStatus.data?.lastRunStage === "failed" ? "border-[#f0d6bc] bg-[#fff7ef]" : "border-[#cce0d7] bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold text-[#245b4d]">{stageLabel(syncStatus.data?.lastRunStage)}</p><span className="text-xs text-[#68756e]">{syncStatus.data?.isRunning ? `${syncStatus.data.lastRunProcessedFolders ?? 0} من ${syncStatus.data.lastRunTotalFolders ?? 0} مجلد` : lastSummary ? `اكتُشف ${lastSummary.discovered ?? 0} · مسودات ${lastSummary.draftsCreated ?? 0} · موجود ${lastSummary.existing ?? 0} · فشل ${lastSummary.failed ?? 0}` : "راجع الخطأ ثم أعد المحاولة"}</span></div>{syncStatus.data?.isRunning && <Progress value={progress} dir="rtl" className="mt-3 h-2 bg-[#dcece1] [&_[data-slot=progress-indicator]]:bg-[#2c725a]" />}{syncStatus.data?.lastError && <p className="mt-2 text-xs text-[#9c4b25]">{syncStatus.data.lastError}</p>}</div>}
      {treeOpen && <div className="mt-5 space-y-5"><div className="rounded-2xl border border-[#e4ede7] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#183d35]">معاينة الشجرة</p><p className="mt-1 text-xs text-[#68756e]">المعاينة قراءة فقط؛ لا تنشئ منتجات.</p></div>{treePreview.data && <div className="flex flex-wrap gap-2 text-xs text-[#536d61]"><span className="rounded-full bg-[#f7fbf8] px-3 py-1.5">{treePreview.data.summary.categories} تصنيفات</span><span className="rounded-full bg-[#f7fbf8] px-3 py-1.5">{treePreview.data.summary.products} مجلدات منتجات</span><span className="rounded-full bg-[#fffaf0] px-3 py-1.5">{treePreview.data.summary.needsReview} تحتاج مراجعة</span></div>}</div>{treePreview.isLoading && <p className="mt-3 flex items-center gap-2 rounded-xl bg-[#f7f4ed] p-3 text-sm text-[#68756e]"><RefreshCw className="h-4 w-4 animate-spin" />جارٍ قراءة الشجرة…</p>}{treePreview.error && <p className="mt-3 rounded-xl border border-[#f0d6bc] bg-[#fff7ef] p-3 text-sm text-[#9c4b25]">{treePreview.error.message}</p>}{treePreview.data && <ul className="mt-4 space-y-2"><CatalogTreeNode node={treePreview.data.root as TreeNode} /></ul>}<div className="mt-4 flex flex-wrap items-center gap-2"><Button onClick={() => syncTree.mutate()} disabled={!canConfigure || syncTree.isPending} variant="outline" className="border-[#b9d3c6] text-[#245b4d]">{syncTree.isPending ? "جارٍ حفظ التصنيفات" : "اعتماد/تحديث التصنيفات فقط"}</Button>{syncTree.data && <span className="text-xs text-[#245b4d]">أُنشئ {syncTree.data.created} وتحدّث {syncTree.data.updated}</span>}</div></div>
        <div className="rounded-2xl border border-[#e4ede7] bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-bold text-[#183d35]">معاينة الأقسام والمنتجات</p><p className="mt-1 text-xs text-[#68756e]">اختر قسماً لمراجعة ملفات المنتجات قبل الاستيراد. الاستيراد الفعلي يتم بالزر الأعلى.</p></div><select value={selectedGroupId} onChange={event => setSelectedGroupId(event.target.value)} className="h-10 min-w-56 rounded-xl border border-[#d8e5de] bg-white px-3 text-sm text-[#30483e] outline-none focus:ring-2 focus:ring-[#9bc7b1]"><option value="">اختر قسماً</option>{groups.data?.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div>{groupPreview.isLoading && <p className="mt-3 text-xs text-[#68756e]">جارٍ فحص ملفات القسم…</p>}{groupPreview.data && <div className="mt-3 space-y-2">{groupPreview.data.entries.map(entry => <div key={entry.productFolderId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#edf0eb] bg-[#fbfcfa] p-3"><div><p className="font-bold text-[#28463b]">{entry.productCode}</p><p className="text-xs text-[#68756e]">{entry.metadata?.name ?? "بيانات ناقصة"} · {entry.imageCount} صور · {entry.documentCount} ملفات</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${entry.state === "ready" ? "bg-[#e4f3ea] text-[#17633b]" : entry.state === "already_exists" ? "bg-[#f1eee7] text-[#635d53]" : "bg-[#fff1de] text-[#a35d1c]"}`}>{entry.state === "ready" ? "جاهز للاستيراد" : entry.state === "already_exists" ? "موجود؛ لن يتكرر" : "يحتاج مراجعة"}</span></div>)}</div>}</div></div>}
    </>}
    {!isSelected && <p className="mt-4 flex items-center gap-2 text-xs leading-5 text-[#68756e]"><ShieldCheck className="h-4 w-4 text-[#a47d40]" />الاتصال والجذر ومعاينة الشجرة معزولة حسب المتجر. إعدادات Microsoft السرية تُدار من صفحة إعدادات OneDrive.</p>}
    <Dialog open={pickerOpen} onOpenChange={open => { setPickerOpen(open); if (!open) setPickerPath([]); }}><DialogContent dir="rtl" className="max-w-lg"><DialogHeader><DialogTitle>اختيار جذر شجرة المنتجات</DialogTitle><DialogDescription>افتح أي مجلد متداخل ثم اعتمده كجذر. التغيير لا يحذف ملفات OneDrive أو منتجات المنصة.</DialogDescription></DialogHeader><div className="mt-2 flex flex-wrap items-center gap-1 rounded-xl bg-[#f7fbf8] p-2 text-xs"><button type="button" className="rounded-lg px-2 py-1 font-bold text-[#245b4d] hover:bg-white" onClick={() => setPickerPath([])}>OneDrive</button>{pickerPath.map((item, index) => <span key={item.id} className="flex items-center gap-1"><span className="text-[#8ca095]">/</span><button type="button" className="rounded-lg px-2 py-1 text-[#416153] hover:bg-white" onClick={() => setPickerPath(pickerPath.slice(0, index + 1))}>{item.name}</button></span>)}</div><div className="mt-3 max-h-[50vh] space-y-2 overflow-y-auto">{(active ? children.isLoading : roots.isLoading) && <p className="flex items-center gap-2 rounded-xl bg-[#f7f4ed] p-3 text-sm text-[#68756e]"><RefreshCw className="h-4 w-4 animate-spin" />جارٍ قراءة المجلدات…</p>}{(active ? children.error : roots.error) && <p className="rounded-xl border border-[#f0d6bc] bg-[#fff7ef] p-3 text-sm text-[#9c4b25]">{(active ? children.error : roots.error)?.message}</p>}{folders?.map(folder => <div key={folder.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#e3e9e4] bg-white px-4 py-3"><span className="min-w-0 flex-1 truncate font-semibold text-[#28463b]">{folder.name}</span><div className="flex shrink-0 gap-2"><Button type="button" size="sm" variant="outline" onClick={() => setPickerPath([...pickerPath, folder])} disabled={selectRoot.isPending} className="border-[#b9d3c6] text-[#245b4d]">فتح</Button><Button type="button" size="sm" onClick={() => chooseFolder(folder)} disabled={selectRoot.isPending} className="bg-[#183d35] text-white hover:bg-[#245b4d]">اختيار</Button></div></div>)}{folders && !folders.length && <p className="rounded-xl bg-[#f7f4ed] p-3 text-sm text-[#68756e]">لا توجد مجلدات داخل هذا المسار.</p>}</div></DialogContent></Dialog>
  </section>;
}
